### ISSUE TITLE
Feature request: Add support for CraftHead

### ISSUE THREAD

**Issue by KoxSosen** [Dimitri-Bit/Liberty-Bans-Web#3]
The Mojang profile api according to [wiki.vg](https://wiki.vg/Mojang_API#:%7E:text=This%20rate%20limit%20is%20around%20200%20requests%20per%20minute) has a rate limit of 200 requests per minute. While, it is unlikely that users running the web interface will hit this limit, implementing an option for another service that doesn't have such limits would be a great idea in my opinion. One service that does this well is [CraftHead](https://crafthead.net/).

To be honest, I'm not exactly sure how well it applies to this application, but I figured I'd open a feature request in case it turns to be useful.

**Comment by Dimitri-Bit** [comment]
That's a good idea, its unlikely that anyone would use those 200 requests per minute considering that we do cache the Mojang API results but its better to be safe then sorry.
